//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanTopServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long Id { get; set; }
        public string User { get; set; }
        public string Content { get; set; }
        public string Recipients { get; set; }
        public bool IsVerify { get; set; }
        public bool IsSend { get; set; }
        public bool IsSubmit { get; set; }
        public System.DateTime SubTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public bool IsQueue { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> VerifyTime { get; set; }
    }
}
